name: 'Soda Core'
description: 'Run Soda Core Scan'
branding:
  icon: 'check-square'  
  color: 'green'

inputs:
  data_source:
    description: 'Data Source name'
    required: true   
    
  configuration:
    description: 'Configuration file'
    required: true    
 
  checks:
    description: 'Checks file'
    required: true    

  month:
    description: 'Month'
    required: false   
    
  date1:
    description: 'date1'
    required: false    
 
  date2:
    description: 'date2'
    required: false    

  user:
    description: 'db user'
    required: false    
 
  password:
    description: 'db password'
    required: false   

  query:
    description: 'query total'
    required: false   

runs:
  using: "docker"
  image: docker://nizolli/sodaqa-month:v01
  args:
    - ${{ inputs.data_source }}
    - ${{ inputs.configuration }}
    - ${{ inputs.checks }}
    - ${{ inputs.month }}
    - ${{ inputs.date1 }}
    - ${{ inputs.date2 }}    
    - ${{ inputs.user }}
    - ${{ inputs.password }}        
    - ${{ inputs.query }}
